"source": [
    "# scale image's intensity to [0,1] with mean value of 0.5 for better visualization.\n",
    "def intensityscale(raw_img):\n",
    "    \n",
    "    # scale an image's intensity from [min, max] to [0, 1].\n",
    "    v_min, v_max = raw_img.min(), raw_img.max()\n",
    "    scaled_im = (raw_img * 1.0 - v_min) / (v_max - v_min)\n",
    "    \n",
    "    # keep the mean to be 0.5.\n",
    "    meangray = np.mean(scaled_im)\n",
    "    scaled_im = scaled_im - meangray + 0.5\n",
    "    \n",
    "    # clip to [0, 1]\n",
    "    scaled_im = np.clip(scaled_im, 0, 1)\n",
    "    \n",
    "    return scaled_im\n",
    "\n",
    "im = cv2.imread('einsteinandwho.jpg') / 255.\n",
    "im_scaled = intensityscale(im)\n",
    "plt.imshow(im_scaled)\n",
    "plt.show()\n",
    "\n",
    "# TODO"
   ]
